<?php

namespace App\Http\Controllers\Finca;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\biotrackcmdphp\BioTrackCmd;
use App\Http\Controllers\Finca\UserController;
use App\Http\Controllers\Finca\UserBiometric;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\Finca\Device_UserController;
use App\Http\Controllers\Finca\UserFaceController;
use App\Http\Controllers\Finca\UserFingerprintController;
use App\Device_User;
use App\Device;
use PHPUnit\Framework\Exception;

class BioTrackCmdController extends Controller
{
	/**
     * Funcion userByDevice busca y lista todos los usuarios
     * por dispositivo.
     *
     * @param  number  IP
     * @return json  respuesta
     */
    public function userByDevice(Request $request){
        //Validacion de campos que se pueden recibir
        $this->validate($request, [
            'IP' => 'required',
            'Type' => 'required'
        ]);

        try {

            $cmd = new BioTrackCmd (request('Type'), request('IP'));
            

	        if (!$cmd->get_users()) {
	        	return response()->json(['respuesta'=> 'No hay usuarios en este dispositivo.'],422);
	        }else{

                $cmdResponse = $cmd->get_users();
               
                $ids = [];
                foreach ($cmd->get_users() as $user)
                {
                   array_push($ids, $user['userId']);
                }

                $sorted =  DB::table('User')
                            ->join('Department', 'User.IdDepartment', '=', 'Department.IdDepartment')
                            ->whereIn('IdUser', $ids)
                            ->orderBy('User.Name', 'asc')
                            ->get();

                return response()->json(['respuesta'=> $sorted],200);
            }

        } catch (Exception $e) {
        	return response()->json(['respuesta'=> 'Error inesperado userByDevice BioTrackCmdController.'],422);
        }  
    }

    /**
     * Funcion inject_user_to_device inyecta directamente al dispositivo un 
     * nuevo usuario. El parametro $data contiene las huellas, rostro del empleado
     * y otros datos necesarios.
     * Ejemplo:
     * $data = [
     *       'userId' => $id,
     *       'userName' => $name,
     *       'userPassword' => '123456',
     *       'userPrivilege'=> 0,
     *       'userCardNumber'=> '',
     *       'userEnabled'=> true,
     *       'userFingerprints'=> [
     *           $fingerprint[0],
     *           $fingerprint[1],
     *           $fingerprint[2],
     *           $fingerprint[3],
     *           $fingerprint[4],
     *           $fingerprint[5],
     *           $fingerprint[6],
     *           $fingerprint[7],
     *           $fingerprint[8],
     *           $fingerprint[9]
     *       ],
     *       'userFace'=> ''
     *  ];
     *
     * NOTA: esta funcion es llamada en el controlador RegisterUSerController.php
     *
     * @param  string  ip_device
     * @param  array  data
     * @return boolean  true
     */
    public function inject_user_to_device($type, $ip_device, $data)
    {
        $cmd = new BioTrackCmd ($type, $ip_device);
        return $cmd->update_user_data($data);
    }

    /**
     * Funcion add_user inyecta directamente al dispositivo un 
     * nuevo usuario sin huellas, ni rostro.
     *
     * @param  string  ip_device
     * @param  string  user_id
     * @param  string  name
     * @return boolean  true
     */
    public function add_user($type, $ip_device, $user_id, $name)
    {
        $cmd = new BioTrackCmd ($type, $ip_device);
        return $cmd->add_user($user_id, '123456', $name);
    }

    /**
     * Funcion delete_user_to_device ELIMINA DIRECTAMENTE del dispositivo un 
     * usuario TODA la información de este.
     *
     * @param  int  IdUser
     * @param  string  IP
     * @param  int  IdDevice
     * @return json  respuesta
     */
    public function delete_user_to_device(Request $request)
    {
        //Validacion de campos que se pueden recibir
        $this->validate($request, [
            'IdUser' => 'required',
            'IP' => 'required',
            'IdDevice' => 'required',
            'Type' => 'required'
        ]);
        $cmd = new BioTrackCmd (request('Type'), request('IP'));
        $IdUser = request('IdUser');
        $IdDevice = request('IdDevice');

        /*NOTA:
            CUIDADO REALMENTE LO DESAPARECE DEL DISPOSITIVO*/
        /*$del_user = $cmd->delete_user($IdUser);

        if ($del_user) {
            $device_UserController = new Device_UserController();
            $del_device_user = $device_UserController->deleteDeviceUser($IdUser, $IdDevice);
            if ($del_device_user) {
                 return response()->json(['respuesta'=> 'Empleado eliminado con éxito del dispositivo.'],200);
            }else
                 return response()->json(['respuesta'=> 'Error no se elminino localmente funcion delete_user_to_device.'],422);
        } else {
             return response()->json(['respuesta'=> 'Error no pudimos eliminar el empleado del dispositivo.'],422);
        }
*/
        try{
            $del_user = $cmd->delete_user($IdUser);
            $device_UserController = new Device_UserController();
            $del_device_user = $device_UserController->deleteDeviceUser($IdUser, $IdDevice);
            if ($del_device_user) {
                 return response()->json(['respuesta'=> 'Empleado eliminado con éxito del dispositivo.'],200);
            }else
                 return response()->json(['respuesta'=> 'Error no se elminino localmente funcion delete_user_to_device.'],422);
        }catch(Exception $ex){
            return response()->json(['respuesta'=> $ex->getMessage()],422);
        }

        return response()->json(['respuesta1'=> $del_user],200);
    }

    /**
     * Funcion data genera un estructura json necesaria
     * para registrar un empleado hacia el dispositivo fisico
     *
     * @param  int  id
     * @param  string  name
     * @param  string fingerprint
     * @return json  data
     */
    public function data($id, $name, $fingerprint)
    {
        $data = [
            'userId' => $id,
            'userName' => $name,
            'userPassword' => '123456',
            'userPrivilege'=> 0,
            'userCardNumber'=> '',
            'userEnabled'=> true,
            'userFingerprints'=> [
                $fingerprint[0],
                $fingerprint[1],
                $fingerprint[2],
                $fingerprint[3],
                $fingerprint[4],
                $fingerprint[5],
                $fingerprint[6],
                $fingerprint[7],
                $fingerprint[8],
                $fingerprint[9]
            ],
            'userFace'=> ''
        ];

        return $data;
    }

    /**
     * Funcion actualizarEstadoActivo actualizar el estado del empleado 
     * sobre los dispositivos en terminos de acceso
     *
     * @param  int  user_id
     * @param  string  estado
     * @return boolean  true
     */
    public function actualizarEstadoActivo($user_id, $estado)
    {
        $actualizarEstadoActivo = DB::table('Device_User')
                ->join('Device', 'Device_User.IdDevice', '=', 'Device.IdDevice')
                ->where('Device_User.IdUser', $IdUser)
                ->get();

        return response()->json($actualizarEstadoActivo,200);
        /*traer lista de dispositivos para desavilitarlo de todos
            EN PROCESO ESTABA VIENDO QUE DEVUELVE ESTE QUERY*/
    }

    public function get_users_by_device(Request $request)
    {
        //Validacion de campos que se pueden recibir
        $this->validate($request, [
            'IP' => 'required',
            'Type' => 'required'
        ]);

        $cmd = new BioTrackCmd (request('Type'), request('IP'));
        //return $cmd->get_users();
        return $this->data($cmd, 9009);
    }

    /**
     * Funcion open_door abre puerta de dispositivo enlazado.
     *
     * @param  string  IP
     * @return json  respuesta
     */
    public function open_door(Request $request)
    {
        //Validacion de campos que se pueden recibir
        $this->validate($request, [
            'IP' => 'required',
            'Type' => 'required'
        ]);

        $cmd = new BioTrackCmd (request('Type'), request('IP'));
        $open_door = $cmd->open_door();
        if ($open_door) {
            return response()->json(['respuesta1'=> "Bienvenido."],200);
        }else
            return response()->json(['respuesta2'=> "Intente de nuevo."],200);
    }

    //INICIO FUNCIONES DE PRUEBA
    /*Abreviatura:
        - número positivo: funciona en cualquier dispositivo
        - número negativo: no funciona total o correctamente en cualquier dispositivo
        - sin número: no se realizo la prueba en cualquier dispositivo
    */
    //Andministracion A = 10.203.231.200  >>1,2,3,4,5,6,7,8,-9,10,11, ,13,14,15,16,17,18,19,20,21,22
    //Despalillo = 10.203.231.192
    //Empaque 4 = 10.203.231.185
    //Produccion 2 = 10.203.231.187
    //Produccion 3 = 10.203.231.188
    //Andministracion B = 10.203.231.180
    //Servidores = 10.203.41.39 >>1,2,3,4,-5,-6,-7, , , , , , , , , , , , , ,21,22
    
    //1
    public function get_serial()
    {
        $iPP = '10.203.41.39';
        $cmd = new BioTrackCmd ('bw',$iPP);
        return $cmd->get_serial();
    }

    //2
    public function get_firmware_version()
    {
        $iPP = '10.203.41.39';
        $cmd = new BioTrackCmd ($iPP);
        return $cmd->get_firmware_version();
    }

    //3
    public function get_fingerprint_version()
    {
        $iPP = '10.203.41.39';
        $cmd = new BioTrackCmd ($iPP);
        return $cmd->get_fingerprint_version();
    }

    //4
    public function get_device_info()
    {
        $iPP = '10.203.231.200';
        $type = 'bioface';
        $cmd = new BioTrackCmd ('bioface', '10.203.231.200');
        return $cmd->get_device_info();
    }

    //
    public function get_users()
    {
        $cmd = new BioTrackCmd ('bioface', '10.203.231.193');
        return $cmd->get_users();
    }

    //6
    public function get_user()
    {
        //Servidores = 10.203.41.39 bw
        //Andministracion A = 10.203.231.200 bioface
        $iDP = 9995;
        $cmd = new BioTrackCmd ('bioface', '10.203.231.193');
        return $cmd->get_user($iDP);
    }

    //7
    public function get_user_data()
    {
        $iPP = '10.203.230.240';
        $iDP = 1133;
        $cmd = new BioTrackCmd ("bioface",$iPP);
        $data = $cmd->get_user_data($iDP)['userFingerprints'];
        // if ($data[3]) {
        //     return response()->json(0,200);
        // }else
        //     return response()->json(1,200);
        return $data;
        
    }    

    //8
    public function delete_user()
    {
        $iPP = '10.203.231.190';
        $iDP = 1;   
        $cmd = new BioTrackCmd ($iPP);
        return response()->json($cmd->delete_user($iDP),200);
    }

    //9
    public function delete_user_password()
    {   
        $iPP = '10.203.41.39';
        $iDP = '9987';
        $cmd = new BioTrackCmd ('bioface', $iPP);
        return response()->json($cmd->delete_user_password($iDP),200);
    }

    //10
    //Borra las marcas no sus huellas de empleado
    public function delete_user_fingerprints()
    {   
        $iPP = '10.203.41.39';
        $iDP = '9987';
        $cmd = new BioTrackCmd ($iPP);
        return response()->json($cmd->delete_user_fingerprints($iDP),200);
    }

    //11
    public function delete_user_face()
    {   
        $iPP = '10.203.41.39';
        $iDP = 9987;
        $cmd = new BioTrackCmd ($iPP);
        return response()->json($cmd->delete_user_face($iDP),200);
    }

    //12
    //CUIDADO!!!
    public function delete_all_users()
    {   
        $iPP = '10.203.41.39';
        $cmd = new BioTrackCmd ($iPP);
        return response()->json($cmd->delete_all_users(),200);
    }
    //CUIDADO!!!

    //13
    public function enable_user()
    {   
        $iPP = '10.203.41.39';
        $iDP = 9987;
        $cmd = new BioTrackCmd ($iPP);
        return response()->json($cmd->enable_user($iDP),200);
    }

    //14
    public function disable_user()
    {   
        $iPP = '10.203.41.39';
        $iDP = 9987;
        $cmd = new BioTrackCmd ($iPP);
        return response()->json($cmd->disable_user($iDP),200);
    }

    //15
    public function add_user2()
    {   
        $iPP = '10.203.41.39';
        $iDP = 9987;
        $nAME = 'Pepito';
        $pASSWORD = '123456';
        $cmd = new BioTrackCmd ($iPP);
        return response()->json($cmd->add_user($iDP, $pASSWORD, $nAME),200);
    }

    //16
    public function update_user_name()
    {   
        $iPP = '10.203.41.39';
        $iDP = 9987;
        $nEWNAME = 'Pelusin';
        $cmd = new BioTrackCmd ($iPP);
        return response()->json($cmd->update_user_name($iDP, $nEWNAME),200);
    }

    //17
    public function update_user_password()
    {   
        $iPP = '10.203.41.39';
        $iDP = 9987;
        $iType = 'bioface';
        //el max de caracteres permitidos es 8 si agrega mas corta el texto hasta el tamaño requerido.
        $nEWPASSWORD = '12345678';
        $cmd = new BioTrackCmd ($iType, $iPP);
        return response()->json($cmd->update_user_password($iDP, $nEWPASSWORD),200);
    }

    //18
    public function update_user_fingerprint()
    {   
        $iPP = '10.203.231.200';
        $iDP = 9987;
        //indice izquierdo
        $iNDEX = 3;
        //fingerprints 3 (indice izq.)
        $fINGER = 'TBtTUzIxAAAFWFsECAUHCc7QAAAdWWkBAAAAhYU0m1hGAAEPVwCIAGNXlABvAGMPFABqWB0PqQB+ANIPZliCAFkPhgBIAOxXlQCRAAMPDgCQWCkPjgCjADkOvFilADIPmQBtAFBWpQCoADgOpgCpWE4PRACwAJEPkVi0AFIOoAByAE5WrwC8AEAOFAC5WDUP4gC/AOgP/ljEAKkPgQAXANZXTADTAFMPRQDYWM8OyADdAIAP1FjgAD0P9QAmAC5XjQDqANgPuQDuWNUOdADtAA0N0Vj3AEQP4AAzADZXowD4AGAPoQD7WNENbgD+ACQNllj/AGkPVQDOAedVagAQAe0NgwAQWecOVQAcATkO61gjAa8PawDhAXlX1wApAegPTwAvWegPXQAuAT0P/FguAYcPzQD+AfxXAQE+AYYPvwBHWfMPQwBHAcIPglhKAfYPwgCOAfNXy6K77p/nlg42XxpnOU5yfadhq67XB7fvBbYIF99qN3FqDjdZYOjMtsOUCRzNCXCyuKIjDpL2lKuU+bz1yP0xDqH36R+5A3wEyOeV7Gjpq6Tz+ipXKgSnAQKmNQv9/OFZeftAVAAU0fTtCtQTUFDvBZrx3fiYh6+qYH8igGJ3NQfwWtz/5gEGB4KMcaf8/NX5TAusAwNJ1ft9+WkPfPsb3NvxJQRJDRhxIVZ4CKn8sPbA6ZClPRP5CekDCfPwozALkfi5i2uOtavg5RXxIBOoGeCtCAjJkbaUJOgMpYAVWQ1FHRBxqLSEBb7xFRiAHLBd9ChFyvooqITAyZSC7fGNOmdh9KMjbN70cXz8/V9UKACd2IKhJAVYSW9OqQCm2EqgrKRoCz55WhGODDp5JARODDN8oP1nSg4DeyRBZPZPB3hGAQLDIZ7AAH5zcX4IAKskssHFmcDC/gQA2vGPjVMBqyx6g8AH/8cTCACiRPoqBcD6pggAmkl0g7XADFijSQAzSv3VAOoQloSIwsDBvVkGWFdRYsERAD5Zkph5wpbBeF3XAMkzkcGRw4vBBP9tNgYA1G4XPoAGBcpxacKLCAARcyUD/kAIAPp3WXjF0Q0An1B3wwTAx5jBXcERAGa63sWm/v79M0Y+BRAF8oET/ilXwQXAxJjDwAYAX4OS/8UXBwBjh1fABVcIWIeJ3v0gQYPBFViLjOT+/Pw5wPqn/sDAwf7COgkF2pFWdHDCD8WWla/6/CpS/1IGCAXElHTHwIPBzwDLzyjAwFZZD8WSmqj5/Pv/wP46NfhtEQC9pi0vhMAmd/8NALmoMf39+pn//vw9BABSq1nfCwClqzT+6yPGWwFfr1DACsVktRT+/3b//P7BAEfrW3YGAJuwjP76HAUAk7lP/zsHBca6TP/+wDrAAKbjSP/+/wUAa8A/pigLANLANAXBYNjFAwDjwS0FCAX9yUb9/i3+3wECl6r/eHiCxAbCx5jDwMHBwf8HKR5ZDs2tZMJrScLB1nXAW/53CMVc1hFG/SQEAEkTV2FdAU/XUP9J1QDCuEE1/f1Bwjv9xQwFAPnlK2/AAPG/MX4WAHjrCcL6pv78/Pb7wDnA+6f+/v3A//87GwUy9cZWMf//Ofr4pf//wP/A/wTAxCnDBwCe+V46//t1DgDR+UD+OP09p/4yUQoA1jw9+qT8//8wBAAk+jGYwgYAo/xXOP89WxGPAGfABtVnFC/C/ZEEEGfkfWlcEfIkHIgF1WciL1AHEIYscDr9YFQR0ixkwDg4//ucLAYQ0Dft2/0BSPg8iZ8IEAw+Z6b/wfxHBhHOR4yZiggRAE2GB8JXpwcQO1AQwzt9Akj+VIB7V1KHAA4b';
        $cmd = new BioTrackCmd ($iPP);
        return response()->json($cmd->update_user_fingerprint($iDP, $iNDEX, $fINGER),200);
    }

    //19
    public function update_user_face()
    {   
        $iPP = '10.203.41.39';
        $iDP = 9987;
        $fACE = 'vgTiAQABBwAAAAAAAAAAAFpLRmlYATFLFKboAUQBQ1Mg+fgXcjTwrDJ7MrsDagLrB3kM2ycZbZsOrw2Pmu8DpwOzA/Ij4GdgYXMQ92XLaJsk73r6HPlyZlaZbaIMj0yaDA1NtjNHI8YzZzNnsyOYc7eDGZO2i5mj+qx1oD1CZWRNop1LFcMNcz9sFu4DZgdmmbcZM46zHberpk2nga8Js6jgD2MvYR9Dr8ovSzV4POpTTDdg5zP/M/kzvTMtoWyFqwPMg6yR3NH5k9yRXsntwXFh9eMzJjMgezJrMuZwL5LlMcSVJ1uMmQ1T3Jcdr02KJu4l5mHJ5mPzInNi/zJzMuImcxfxtOE1oLSBPQU/DScPKw1vZucnZ/bx53PmcnUj8yNxI/Ix8rKxMPE1GrSTNRpmGSZDpxkmMuNZrjmzNTttB7cDc5Nlk2WxJLPnsmWxg7WDJRJ2E+ZTtjG3U5kxHTkTORk8E98LBAADAwACAgEBCgMEAynBBwUYHP8aAAcbKCEUAQEADgEDCgcBAhc1Bg4HD8wcAAMUDgABBQsBDQYCCAUEAAoDBRAABhFPCQsh3RwFDRtWNgkJBjJRHgICAQkIHBcCAAUNRxIGABpAFwYGwiEFASkFAAcCDQkEAAEFAQMpAQI3bgQDLJIyAgQPhA8CAgEYfRIBAQAIDHYPBAQDGEMRAwINiBsDAD4bCAIlBgwGAQALBAcBDAMDJAEEKrQFCSyIJAQEDiAjAgMDDzYPDgEBFhxBKQUDBS43Gw0BDtwxBgk2FgAADgECBgEFBgQCAAMBAhgBAwSNAQQHBwsEAwgKCwEPAxZECwYIAxEX/xwCAgwnGxwDAxEJCw0CgwoLBBoGAQAAAwYBAQAAAAAAAAEAAAEAJnkBAANp/yEAAAIR/4cAAAABAAAAAAAAAAAAAAAHEgAAAAMEAAAKBQANAwEACAUBBgQNNAAMKXAGBjf/KAIHEnIlBgYIEDoTBwIACxdhIBAIAB9+HA8DBzMYAwUIBAMBCwQDAgEDCAgIAwwABB0CBRl8BgkgmxgEDxR+LgkKCCRIFAkAAQoXYSoEBAUhYxgEAhhfEQYFYhYEAB0GAQoAAwsFAwAFAQc3Aw41/wMMPWgzAQUcVC0SCQUQ0SAVAQALD0cnAwcGFx0NBgALFwMEASAHBAEXAgECAQQHAgAAAgACIwABAnsCAQQAAQIAAAEBAQEBAgEBAAAAA0//EwEBARj/hAEABwwVAwACAwUCAQABAAAABAEAAAAAAAAAAAAAAAABAAACAUZ0AwAAAR//aQQBAAEAAAAAAAEAAAAAAAEBAAAAFAEAABgCAAkCAQEDAAMFBAYEAAECIAACJXURAAUopSkBCghP/yUAAAACDTsZCgECDyMUBQIRaAkCAGILAgBOBAAGAAQFBQIBCQICEwACKsAICD7oGQEPEpAfAQEHKS4SBQAABQcKDAIBBB0XBAgAIIgWBgl1IwIAIgEACgELCgUAAAIDAi0ABAZwAQUJLxECBg9kFQcEBiE3FAQAAAoomhsBAwRPyB8BAB6HPAYDThgKARgBAgMBBwQBAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABRnEDAAIAHf9oBAAADSgGAAACBAMAAAIAAAAFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC+BOIBAQEHAAAAAAAAAAAAWktGaVgBMUsUjugBRAFDUyD5+BfwtPGsCnkTPQ1rBnsH+wfXdzNJMx+vHZ4aZwM3B3IH8k/gw2CTlpON0ZnZGRnhcvkY4zJldJF5siyXfZpsDmk2B0xPTpfFG2aTk5kHjbM5G7Oh8SP5pfUkecB1Sl2wlUM9wjVDP2cvbDNPD0fHF4h3j5UtBymVSYYBPwm7oegfQ3fAP0GX0hVLM3wPalPAF2DLNnhTeSV5B28Eb4RrQ+yBYTG9EfIT+JFeQX/JM3FOQ3ZFn0D7EHoecVQtl+UJxYcrW+6cYzOtFm085Zo12AVLE3FmyzZzlgZ1EXxP8A1jD+Ea5w9DdkMaEzevJrcPpw/jw6ZPXnHmYfYSNQd1M34L8VhyTGVTMksavhJbkkePX7ZNLFM2yDxhPcVEJ90XNgc3ExtDMdc5w9OaE8rQlZo+E3YBNjCHjZeYl7xHeC98Dxm3NZ4DAAADBQUNAQISJAEDMPoaCA8d5jIBAhUlKBUDAQAOBRIRCwIAFSwJCgQPvBQBBxQKAgIJCwEHCAULBwYABQUHIwIHF2oKBxevKgQKCVwtCgoFIk0VCAABCg0lGgYDBg5vFQwDEUEbBQWcHAoBLwQABwELCAcBAAYEBScAAiJwAQMkVhsABxeEDwIEBhCRHgIBAA0UiRIFAQIaRyACAAt3GQUCWx8HAiILCAgEAAkIBQABAgInAQwm3wMGKXEmAwMNJyEDBQkGIgwKAwAUGDQiBwIEMTQgBwEN/jIDCzMcAwALBQAFAAgJBAAAAAQCHgIEAlsABQcSCQQDBw0OCAkDDzcLCQYBERr/HAMDDicsKAEBEAcKCgKODwgDEgEDAAECBgEAAAADAAEAAAYBAwM1iwMABWD/FwECAx//jgQAAAAAAAEBAAABAAAAAAUCAAAAGwQAACMDAAkAAAALAwIQBA8zAAQoiQoDLPMvAhAOOCUFBwgNFQ0FAQAPGk4rDAYBL7AZGAoRPi0AAh4NAwIHAwYIAQIICgYABAABJgACFJgKAx9xEwMPD2MjBgkIJ1kRBgMDFBlwKgQCAy5TEgcBGXQbCARuFQQAIAYDCAIFCgQCAAQBB1AECyjaAwgmUyQCAx1OGg8EAS64HQ8EABMVkToEAQQYQBoDAQkVBgMCLAMFAikDAgECBQYBAAAAAAAXAAAATwABAAAAAAAAAAAAAQAAAAAAAAADVv8NAQMAEv+KAQAFCxUFAAQCBQIAAgIAAAABAQAAAAAAAAEAAAAAAAMAAAEBSqIAAAIAO/9ZAAABAQAAAAAAAAEAAAAAAAAAAAA1AAABPQEABAAAAwUEAwYBAw0DBRg7BAkxqCADByRfJAIGCkuCJAQCAAQIRiEGAQEUJw8CARh+CwMBhh8AAEoMAAgDBwYNDAAIAgI5AAJD9woFGK07BQkFDRgABAYOBQ0FAAANDSkrBAEBHi4WCwAplCIPC2coBwARBgMJAQ0NBgQAAwICFgEFCyACBBkrGAAFEUknBQYJET0WAgAACiVYFgUBDVr/JAEAE4hTCQA+GA0DDgAEAwABBgIAAAEAAAIAAAMKAQIQGQ4ABgYgBAMCAgsCAAAAAAYyKAoGBgAm/0cHAgoVMQQBIgwFAQEBBwABAAkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAL4E4gECAQcAAAAAAAAAAABaS0ZpWAExSxSQ6AFEAUNTIPn4F/ka+VkjW5oZDcqS+Q35JtcnO1knHrpdmh7PQ7YjYwvio+Al4CuXEcdxixkbNOdw/jLjduYzsnVkDNfdGgyPiZYvTQ/GD0cc5rEHmRekixkPvRO5K/kUfap4an1inSA/QxXCPUM+6B3uF8YP5seHDw/DiS3Dq4ZJxAn+Cfqhuh/HD9Ofww/KR8uPaB3qz0wPJvsLew3zALsD5QHsgOtBzIJpQYyT8RH9kXzI7cjncU3CxwaHAW8Kaxk2TS+f5xrmNkNK5poDN6aWhTyNmozYh15nUUZLfgJ+Im85fRnyl/cPYxtjC0GucxsDNy8zr12nMYLHh2feJc4j/hC9Js8gnRHNMtkk7RM5Swm+G3uLJ5M3pY0hNzhELSMdBJ0nvQefBomHnZMZ4xmjk+YD58OMkTcB7hO3U64TH1iOOQ84DTwPvBVfQgMAAQYBAgIAAAMEAwEy/wYIEhv/KwAEEiIuJwABAAoEAwkJAQEROwkLBhGCFwEDEQMBAAgMAQ0GAwgFAQELAQorAgoriQgMKv8rBAgOTjUHCQccSBAKAgAFDzEiBggCD0sOEgEGLw8HCWoMBgIaAQIEAQkHBgMAAQEFMgADKmgGASVdFwAEFLAUAwQEEVEaAgMACQ6NDAgFARFxEQgDFHUhAwFOIwkAHQcFBgQACgYGAQIBAiQBCjHOAg41ZDIGAxM0IAgFAxJVFxEFAQ8QWSwEBgMZLBwGAhOjJgYMKhcAABEDAQMACgUDAAAAAwApAgcExgAFAwcHBgMKDAoFBwIOPgwJBwEZGf8fAgMPHScYAgALBwoNBIYMBgMWAQIBAQMKAwAAAAAAAAAAAgABAhEhAwAFZ/8GAAEBFf+iAAAAAAAAAAAAAAAAAAAAAgUAAAAEBAAADwUACQAAAAkBAQsDEDMACSk5BwI9/ygBDROGHgMFBBsbEAcAAAQhPh0XBwEnqB0TBQZzIAECFAwBABEEBQYAAQUKEAEJAQMjAAIaiQ4HF3sVAg8XOiMDBg0sSw0KAAIXFUYjBwEEJlIYBgEglxUKB3scBQEkBgQPAAoMBwMAAwcMNwINI/QECjhBJAMDJVsmDQUEJLkrDgQDExBvLwYHBg0nEAQCDh0KAgE5DgMAJQIBAgMEBAEBAAAAAB8AAAMzAAADAQAAAAEAAQAAAAEAAAABAQZp/woAAAIb/5sAAAYJGAYBAwUFAQAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAEmSAEAAAEj/zcCAAAAAAAAAQAAAAAAAAAAAAAAABABAAAjBAAEAgIGBAAAAgABCQABCjAAASW0GwADJH0WAQcGYf8fBAAABwpDGAMAAA4dEAEAEh4HAAJqCAIAVgMACAIEBgoIAAUAAiUBAjP0CBEk5i0BAwwiGQMDBBoXBxAAAAwURhoCAAUXIBIKACSYGgUMTS0CABADAQYBCQgCAAEAAgIcAAEGYAACDDcZAQISRyICBggYIRQBAAAGKE0TAAAJbP8eBAASdmUIAigUCgAUBAMCAAECAwIAAgIAAwAAAQEAAQMBAAABBBIBAAQCBAIBAgAADCkvBAMIAS//SgsDAykhEwYFAwkGAgAIAAAAFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAvgTiAQMBBwAAAAAAAAAAAFpLRmlYATFLFJToAUQBQ1Mg+fgXcJx5riXLPWoN7gbrHf0y0xubHbMeixybnm+zpBubi+Ib4wnghXcJzyHLGc8k53CPMsV2phTFNWAM151bDAsNFwwvHEcfRw3no6OZT4VDCau4lfmr+JT8qjltPGIdIL1BNUI1Qx1sHGoPJA9mw4WPD8HJLYkrpmnGCf8J+qG+HsOPw4/JD+sHyYx4XGnfJBtg20n7DdmAeaXhM+6Fq0PMwHNh1NDxkfWAXqhkyJzRTOHbIm8EPwhrGTHdK53jFeIdBR4K3ScTFdNTK2erRm4j7sxYy2meFGthnUl9CXCN9A3LDI0dq1yNTQsfDU9HCw8vakdpL15BzSGfEW0nzQOdgc2R3ITNm5kNQqyLLUM2EzbYVkk+es15DJlGGQ3ZB48NjYO9g1mRONHdkhnTw8uDOQG+k75TzzO+mZ05DpkOuQz8L+csBAIAAwICCgABFxYBCjj/EAERFMIwAQIHLiUgBAAACQUFCgcAABZFBgsHGIYdAAITDgAADAwAEQgBBgYBAAwCCyoAByaYCgse4jMEBw87JwMIBiA4DQcBAAsSQyoIAQUNYhoQAA02EgQDfw8DAhcDAQMBBgoGBAAEAQUmAQQZTgICHzoKAgIVuAwCBQIVbBgBAwANF74UBQYEF1ETAAQSexIDAWkiDgIlBgsHAwIMCAIBCgIFFwIHP9oHCD+QUQIEGEQoCgUHDUAQFAYADRFIJwQBAycnEwQBCYscBAghCwEBDAEBAgIIBgMHAAACAjwDBQnxAgMGCgsEAggRCgYDAggwDAgEAREZ/y8CAAskNykCABAUFwwDZBEFBQ8BAgEAAQYCAAAAAgAAAAMFCQEGIR8CAgJ6/xIBAgcf/54FAAAAAQAAAAAAAQAAAAADBAAAAQoGAQAXCAAJAQEBCgYDCgQKJwEGMVAGBD68OgMNDmwkBQsKGxkKCAAACBs9Ig0KAyasFxMBE3kpAgQdEwEDEQYDCAIACgYHAQoBAh0ABxmICwoNeh0FCRQ6IQUCBi5JDgwDAQ4SMSYEAgQiWRkRASO7HwcGeicCACcGARACCQcKAwADAQ45Ag8byQQMND0dAgYXTyUNBgoquyUPAQEREl4tCAcIGhAOBwASMwQGCGUPBAEwCAIHAwMLAQAAAQAAGwAAAg4AAQAAAAEAAAAAAQMAAwEBAQAABnn/EQEABBH/mwMAAwwTBQAEBAUAAgAAAQAAAgAAAAAAAAAAAAAAAAAAAAAAAjVJAgAABkX/SQEBAAEAAAAAAAAAAAAAAAQHAAAAJwIAAE8IAAUAAAMCAQAAAgQMAAIGNQUDK4IXAQEqXCEDBANx/hoBAAAEDDQWAwEDER4NBgAVJAUAAtoeAwBoBQQHAAgFCgcACgIDIgEDNcgICjDRLQALDC0mAgIHIRsKBgAABwstHQMAASMUCQQALZwQBwOQMAcAGwIABQAEBgICAAEBASoAAAKGAAEHHBEBCRBXHQIGDxUaFgMBAAskWh0DAgl2/xwCABWnZAgCJRACABEDAgEBAAgBAQABAAAEAAECDgECBBgOAAEEBAAABAMDAAAAAAAFKTsUBgMALv9DBQIAKTQCAQEDAAAAAwIAAAAFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC+BOIBBAEHAAAAAAAAAAAAWktGaVgBMUsUkOgBRAFDUyD5+BfwVvmaJl8zLwHmEmcl/TLTUzFZMx6zHJqWbxKfE7MB47PgseCBlxHXYYcZBxHncuYa43JilLFVcgzTnJscF4y9Gx8fxwtGBOexM5l3pTMZF62TuSP5lHmqeUh9a42wHUEd4g1HFvYd5hdHB+eDtw83grMpN6+2abcJ/wn7odofQy/DP0OPwg/BOOwdblNkM2TTMXsz8fO5sW0xbYCrQ+yRJRHt0e2T/ZFuSOzJsGF0w/MEMwR7MhsReHEbk+ExwpUxU7jZKxMMly0qTapk7mHus2lzYbJiU2F7M30w0rXOF8M1hRWlNIV9BzcNZ08nT0diz2dP8lHzYfYx1SPxI72j+bPYsrEx8DUZtZhVkzeZF1O3WR4S0ntMO1e5TZkTvwKxIzMXsTM4s/GyEbODMZFzEPwR9lO2Ey8WlzMPOUM9A30jmUMEAgEDAQMFAAAODAICNf8JBRkb+CECBBEuIh4JAQAKBQMGBgAAFkcICwgVshQBARUJAQANCgQMBgYLBQEBBwUELwIFInQNBSbXLAYNDlI5AAMGGjcVBAEADgg3JgQEAhA4DQwBEkoYBQilEQQDHgEBCwQMCgYCAQcBBCoAASWDBAMnYw8CChCWDQUGBApoGAUDAA8NbQ4BBQIdWBUFAgqCIgIBbR0FAxkLBwoDAQwHBAILAQQZAAQh5gcJN10oAgMTMxcGBQYOPxQQAQAMED8oAgQEIy4aCwER7CwIDyoXAwAOAwIDAQUKBAABAQMAIQEHCrMAAwcKCQUDBQkMAgUDCkAJBgcBHBj/GAABDScaHgUBDgsQCwarDQ4DEAIBAAACCQMBAAEAAAQAAQUEAgMocAEEBGP/EwABBhH/lgEAAAIBAAAAAQEDAQACAAUMAQAACwYDAQ8DAAkBAAEIBAENBA4/AAUrewgFL/8zBA8KTxwFAwoSGwkEAQANHjItEQUBJ5gYFgQNXx0BBRMMAgEFBAQCAQMNBgQBDQQDHQADF20KBhx3FAAQD1wqAwUFJFQOBQAEDh1TJQYDAShhHAYCGagWBwOLHQUAIgICCAACCQgAAQIEBD0EDy77BQ8yTSYEBhpQIBIDBCLEJBYHABESaCsIBwsYIhAHAg8cBAQBJw4DAR4FAgYAAQcBAQABAQMZAAAEXwABAQEDAAAAAQEBAQEAAAABAAAHUf8EAAAEFf94AAEDChQMAQcDCAEAAAEAAAAAAgAAAAEAAAAAAAAAAAEAAAABSY8BAAAGOf9UAgAAAQAAAAAAAAEAAAAAAgkCAAAoAAEALAIBBQEAAAMBAgQABAgABQUqBQQtnhYBBC2JIwECAlz6IgEAAAMHLxMAAQENJQ4CAhFhBwIEixADAF0KAQ8CAgQJBgADAQEuAQYw/wIHI+MkAAoLIhoEBwcdBwQIAAAKFjggAgADIiARDQAkkxkFB1wkBwEQBQIIBAYKAwEBBAMEIgADAnEDAwsyEwEEEUAWBgUFI0QRBAEBByBYHwEABlL/HgEAFXNJBwFMEwcBFgECAwIGBQAAAAAAAAAAAAEAAQABAQEAAQAAAgAAAAACAAAAAQVDLgICAAIk/2sEAQAkJwQDAAMKAgAAAwAAAggAAAAA';

        $fACE1 = 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAL4E4gEFAQcAAAAAAAAAAABaS0ZpWAExSxSQ6AFEAUNTIPn4F/Fmeaoz5zhrBeYy6y/9I9NHmFm6Dqsdmo5rE+UHuwPij+BX4AGnGcchyxjPJOdwzhLDcuZ2mRUwDBedGwwHjT8PPw9HJ08m55WPmU+kzynHvIP5K/iEfap4SX1rFSA9QRVCNWMO3g3uZ0cPp4eHC0/DZw1vL6Zt5QH/Cfuxuh+DD9OfyyfKJ8nP+G1q00RnIMsL22XxwGnD5YHswOtDzMA1YdzQ8ZP1gD7YPYjMccxz5yLPAMsi62ThzkuW50XizYFbis0jQxTHFQ5F2ka+R67Nccsv5mLHIs8BTWbiz2cH40zFDYzMjU0LXwlPS1sNX85nQR/OM88x71PtDuMBzYHtwWzHTcDJzRilic2fZ5nHM4dJHlrpaxzrJskP6QbtBscnxcNJg2nDneKJy8DmiWEB7DFnQ21hPtstaz55C5kb/E2pTQICAQIAAQYAARAPAwMz/wcIERzzJAMIFSErGQQAAAkDAwgHAAEYRAgKBg2rHAEFDAoBAA8OBA4EAwwGAwAJAgokAgojegoHJOA1BQoSVDkBAggYQBIJAQEEDzMbBQMHEFgRFAAHNBsEBI8VBAAWBAEHAwsKBAIAAgEBLQAFJIACBilbEAEFFJAKBQAFFowWBgQADhCUEQEFAhlOEwMDEGwWBABTIAgBJAYIBwIBCwkIAQgECB0ABjPzAw08iTkBBA8jKAkBCA4zDBQAAA0SOSYBAwMkLhgMAgukJwUNLhAAAQ8DAQkACQgEAQAAAgElAQME4wAGBAkHBgIGBwwCAQMPQAkGBQEaGf8jAgALJjoaAwASBA4NAnsRBwcRAQEAAAUMAQAABAEAAgAABQEAASYtBgADgf8NAAICFv++AAAAAAEAAAEAAAYBAAEAAQgBAAAQAQMAFQQBBQABAQcEAgsGDC8BBDxaDAQ88kIEDQpdKAQIBBYVDgcBAAMZOi0RBwAgoRkTAhF0HAIAGhECAQcDBgMBAgYHBQAIAgMeAQUUegYEHF4VBA8SSCoEBQQuTxQMAgITGEAwAgIHHlcaBgAonxYLCYIsBgAsCQAJAAkMBQUBAAQJQQMPIP8JCTAzFwIEI0IgEw0DIqgjCgQAExByJwgGAhoeBggADyoKBQRZDQEBIQcDBwMFCgIAAAMBAB4AAgIwAAACAAIAAQEAAAEDAQABAAIAAARX/wgAAAMi/3oBAQEIHAUBAQIDAQABAAAAAAIBAAABAQAAAAEAAAAAAgAAAAE3VwICAAAz/1ICAwABAAAAAAABAQAAAAACAQAAABoCAAAyAAIDAQMFAwMABQACBwACBSMCBSh9EgECHoIqAQIFZf8YAAABAww8EwEBBQgfEwMADiwIAAHgDwEAXgQABwMFBQcEAAYAAykCAS7/BAk2zR8BBhMtHAAGBisYBwIAAAYTHB8DAAEkJwkJACqLFQoCaDEDABIBAQgBBgYBAAABAQMbAAAEewMBCC0PAQURQhQGBQsRKxcEAQEFInMQAQAGWf8WAAAYs04GAzMTCQMSAgAAAQUEAgAAAAABAAAAAgkAAAEFCgAAAAABBQMAAgEAAAAABi84DAQBADP/WQIDASQ9BQMAAQMBAAIDAAABBwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAvgTiAQYBBwAAAAAAAAAAAFpLRmlYATFLFIboAUQBQ1Mg+fgX+Fb4qDJ7mPkD7ojpD20s1Wu5Da4ev1yanu8CpgezB/Kv4EtgSQ5Bv2MfSD8h/1H+EvM15jWxfWYcxZ1KDA+JHw9Nh0ePY49j5hfMH+FXBR+xC7EpcSo1qTFqfWMVIT1nFXANZg1zDW+PY49jwxXtjMY7Jwcn4SflMXwx+aH6HeOP4Q/jf+Ff4g6VFbefOcdJ/wR4ZPsM5xbGY4YR0kGMw6s7OMvxEniLfqxkrKqJlKE9Wb8BfwxNxYtMBVzAbsZcDtcC3isTLRsTNmeqQ94HtuvB7mF+QX4h30VXRcVPxk3E3uTOBJuDWQ5Pj1unJ6dP5sanR81j7GHvNE0nXcXXRNzI9MD0wOTIHCzL2Q42HRMkhyUTPJwthp3UTcvJB0wXlMOW4xzjPOOc5hHHVOPBkQy2gZsUdwcf0o07DlgG+YbMv8qOAgIDBAADAgAABAAJAinhBwUYIf8YAgYSNSIgBAEBDwIBAQoBAA87AwwHEpsVAQAlEwAAEwgCEAwGCgcHAAsABRMCBx2BBgUl7SsCEgpCKwUIBSA2FQkAAAYGHRsBBQIWPxAIAhpsFgUEnSACASoFAQcCDAoEAQIFBAMvAgEojAEDInUcAgINig8EBAEVXRIEAgALDZIRBAYDF1gOBwEQhR8EAkgaCwEbCggFBAAIBAIABgQFHQACLukHByaIMAMCDCQVCAAGFTASEAAAEQ07HwUCAiMoFQkBE+0pAghIEgABFAUBAwALCQUAAAMBACMCBQKsAAIACwoJAwYIBwEGARYnCwUHAAgg/xoBABEtPykGAAwTEwgDdAYJBxkEAgEAAQgDAAECCAAJAAMHFQIBMYUJAQcy/yYCBQkf/zkCAQADAQgOAwAAAQQCAgAQDgMDABEIBAAWCwMGAAAEBQYCDQELKQADFCMJACHzEwEHGRcXBgUHGR8QDgIACSlDIwoGBULkLAoFFW1ABQNDGwMAGQUACAAEBwwFAQkDAhwCAiJmCwocah8ECSA/JAIFBjJRGQcAAA0bOiYFAQQ1UhUMACB2Lw4HhSIGAi4EARIACQkGBAECBAQkAQci4QMKLTobBAYaSRYPAgYyzSAKAgEYDicqAgMBHyEZCQEQWhoMAWcXBQI7AAYCAQIHAwAAAQQHLwACBHoAAAgBAQADBCYDAQgCBiEJAAAAAzz/GAYBARX/RgIBCg0HAQEFAwAABAYCAAIAAgQAAAQDAAkBAwEMAwQGBQIBAggKCwQEBUX/DwYCAAMPNQcFBAMfIhACARMUCwEBZRMKAUwGBgUHAw0EAAACAQEKAAQFQwUCJVcXAAYeaCwFBQln6BoFAAAEDjMUBQEEFzwLBQEcGQQAAN4aAgB+BQEIAgIDBQQBCAEBIQADKMIEBDrrGQEHFlUwAwIDJCEOBAAACQ8SIAABASMWCAMAKMMUBQN4JwIADAIABwABBgUCAAQAAiUAAAR9AQEIHxgBBRFbFwMFDhUnFQEAAQcqbCABAgRr+yACAB2ZYQgAKR0IAQ0EAwIAAQcEAQADAQMDAAABAgYCCyQDAgUMSAsDBBAVEAUAAAAJCQcHDggCTP8aBwMTmk4AAggSAwAGAgQFAAMGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC+BOIBBwEHAAAAAAAAAAAAWktGaVgBMUsUtugBRAFDUyD5+Bf2HHIsMRsyrwtrAu8GfQTXI5ttmx+/DZ8C7wOvA7MB8xfwR/ChToHpyZmRPY3xUvkc8TV1O5Epsjy1WZtoBgm/T2YHxlPGN+bTBjhLk4s5m4vBsyHZ4PvgOZSr0j+wu5C/nDnwDuQ+5FdGD+bBBzsvl5cfnxuVia8RtYGuueCZQy1glUCt4CfoDewE7Nug1yCfCzsnuYl5hV2E3YD7g92DsXHZY/Bh+EH+ye7I9SHlaeMk6yDfJPMAtWV8leUFzYFuXIzY1RaclvUkTcoHXmXOttCsye8zbgNvS2dK9AN0B/Sx7NvDU4XZB0UN2zcvLU8WxyxHm8KcwV5KLRfPQazC/0O6wvxhvME+PZxJz0+FT6YpJUs+wzzHHYaMAlxKThaFM4jDqUerwcxKOMFM3YjNDT4HnwSXBZeWJyyevSP8oq4JXgIGAQEAAQIDAQEQCwQDKsIOBA0r/xwBAxE1MxIBAAAJAQcJBgEADigHCgMVwhAAAiQMAQAHBgEIBgALBwQABgUCGgAGF2cICi3NGQUMF2gxAwQEKU4fBwQAEAYaDQIDBhA3CgQBDkUTBALYFwcBOQMDBAEICwUBAAAFACUBDDBWAQQpijECBCRZEQ0FBQ5aJwgDAAkVahICAwEhSRQBACCAHAcAcSYIARoEBQQCAAQHAgIGAwEqAAMpuAIEIqYmBAUKIxQEBgcSHwoGAQAUGk0nAgEFKz8WDAEO7DAGCDQdAgERBQEDAQkFBAIAAAABHgAEA48DAgYJCAQEBxALBwEEDCUJCQQEER7/FAAACzIcGwMAFhMICQKKEgcJEwAAAAEBBwEAAAEAAAAABgMGAAE1KQYAAnH/KgUBBCX/gQMAAAAAAAAAAAAAAAABAAIKAAAACgIAACEEAAgAAAIIAQIFAgQtAAYpUwQFL6AiAw4ZUR8DCAUqLxEIAAEKE00mDQIEMM0QDgEicykBAi8aBAEVCQIGAAELBgUACAMDJgIGH38IAyRTEgMKHrYiAgUDGlsbEAABCRqoFQcCBiJnFggCGTsaBwQ6EQkDIAcKDAMECQkFAAoBBjYBBSmAAwQ0XCMDBBU9HQ4FBTnHEQ8DAgwcRTgCBAgyOB0HARo7HwYDThUCAjUCBQIBAAYABAADAAEwAAADIAEAAAQDAAAAAAAAAAEAAAAAAAADdv8kAQECF/+YAgEAChUHAQQAAwAAAAAAAAABBgMBAgIABwEDBAMEAgMXAgIGKT0NAwQENP85BgIACAcVAwMCAxULCAMAEC0IAwEqEgQBMwYGBgEABQoBAAYFBwoABAkjBwQwWR0BDyFdNAYHCUvOGwEBAQoPIiAJBQchbhcHAx9ZFgUEcRoDAUEEAREABAYPCQEEBQMlAQwvZQkHN5MsARUgUzkFBwkZJRkPAAESER0aAgEGGAcMCAElsBUFDY8mAwAZBAIKAwcRCwQACQUELQAFC2MCBAkpGAIFDy4TBwQLGXkTCQEADidzKgIFC1PCIwQBHX8+DQI2HAkBFgQCBAADCAQBAQIDAQIAAAECAgAAAgMAAggRAgIFBg0QCAAAAQwoJgkDBQdK/zEGAAgtXQUGBQwIAQcFDwADAAkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAL4E4gEIAQcAAAAAAAAAAABaS0ZpWAExSxSo6AFEAUNTIPn4F/JY8K0zWDGtB2sEfwZtBNcvu227Ha8NnwFvA5cD8gPzY7BH4JtNgenZmZE5nfNw+VzzNmUzkTkyPLd5m2kGCZ8LTgfOA+YjZtMuOG+TKzk3m4PzIfqh8+Q5kb3CNbD10H3cvdBP5A/kT0aP5oO1Oy+HtwmvGZWJqhGdgaqx6B1DPeC9QKzINOhM2Azpz6DLIMcp+ynRq3kFXYDdgPuB3YGxcdnR+MH4y/7J7MnMcUxhzwZHIbsMeyj0GTeWxWPNEQ5ajJlxFYyTtx1ligZfZs/n0W5DZhJmIm8ObQnmDe4dhj2HOwsfA58DDw0HGw8HCy7PJk/m0c5h7nY9J98jzYnGYcYp5pmPKU48jy2PH49vYy0vLytiLy4eJ0wnHkdeJ8eiwyO2c16I54oJjcJciz0Gdg82I58PN5GGuQ45B/yCfGPsNgMAAAECBAMAAQ8SAgNB4hAIERz/KQIEFTQ5DgIAABICCgkEAAESKAYKBhK2EgADDQkAAAkGAAUIAwkHBAIGBgQTAwMVXQUJIsUYBREZUSgHDAYwUhIEAAQPCiIaAgEGDVMSCAEOThkFA8AdCQEtAgIIAwgNBQMABAAFIQEGKX8CAShhLwABIHoOAwMDFGgjAAAABBd4BQMBAB9cHwECGpAhBABPHgcBIgMJAgIABAcFAQgEBiQACyKzBQkceCsFAgkuGwIFCQsxDQkBAQsdSywGAwI5ShgJAAz0PwUEIBcBABEEAQIDBgQEAAABAgImAwEGgwABCRQJAwMJBQsIAwEPLgQMBwERIf8dAQAOLR0VAAAVDAYIAKcRCQQTAgEDAAIGAgEAAAAAAAAAAQACATI8AgIDX/8sAAECLf+BAQAAAQAAAAAAAAAAAAAABwsAAAAmBAAAJQQADAEAAQgAAgoEBjwBBSZ0BQU1qx8BDRhEIAULAxQnGAcBAAkeUSwMAgU01BsSAxBQKAYEIg4HAA0EBQMCBwcGBgIGAAAyAQMhjgYEJV8TAgwVliMFAgUkVRIIAAMRIaQpAAQKG2MREAIWQBgKBTEUBgEmAwcOAgMKCAQABQEEOAELIbsCCzFCGgQFFTciDQQFM8kWFQMBDBxZNQQJCCMzFgcCGzAWBwJSEgUAMgMBAQMBBgAAAAQBAyIAAAMpAAAAAQIBAAAAAAABAAAAAAAAAAFV/xkBAAAi/2wCAAMNGgMBBAECAQAAAAAAAAAAAAAAAAADAAAGCAAAAg4FAAMsXAUBAAZV/zsIAQAAAAEAAAAAAAAAAAAGBAAAAGoJAQBHCQADAAAABgIABwIAFwAGCC4CBCRsGwAGJXMlAQQLRqoTAQABDA49IAUABSFaEwgAFmESAQawFgMASAQABwAJBQkGAAcBAzgBBSa9CgQlpx0CChEtEwEDAxkGFQcBABASPSoCAgUlIBEGACq7HwcJhi0CAQ4FAQYAEAoFBAADAgMpAAQHQgAEFB4XAwgTSyUEBgQeKRYBAQARIXAiCQIJU/wZAgAjj0kJAFYkCwMQAQEHAAMFAwIAAAEBAgAAAgQDAAYBAAAABg4AAAEBBwMAAAAAByUcBQUHBkX/LwcCB19aCAAJDg4EAgEEAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAvgTiAQkBBwAAAAAAAAAAAFpLRmlYATFLFLToAUQBQ1Mg';

        $fACE2 = '+fgX8kzxrSLYEL0FawPvBnkF1SMTSZscvQ2fAu8BpwPyB/NToEfgq0yBR8nJ2BnN4XL4XOFzZHORKpI8F32abA5ptm5MD8YvRg9mMYebF7WLOZeHgbEjc6XxJHmRtUBlsJXQPdgV8QzgHOEPRofnj5cLH4eXLdepl4mWAb2B+qF4HWP/Yb1Brcg3SR1pFGlfRgdgcwP/GfsDfQVtgOyAa0PMgeERndPwAfnJ/sj9yW1hVcHmQ9cAOwp7GXdtL57lIcyZL1uMmWcRjZ81P0WKFt4FTm3RxkNmAsYFLzt7C2IfYw/hLYM9Kx+DHQMfD0cPKw8vJscmb+7hzmPOKc0X1wHVQ/uEcQKZLbk9Dy2PLY8/iy9HDw0uOsc5Lh8ljSdjD+YPw2PEY0ijbWOBpgmVyz2BPQ4uCS4LjgmPEw8ZD3kHuY26T+ZNAgEBAQIEBQAAEQ8CAD/LDwQJJv8wAAETNzAfAQACCAQDCgIBAhYoCQgGGqgWAQQUDgEADQoCCQUDBgkJAQYFBiIBAxxgBwgbxSUDBw5DKgMICycrFwUAAg0ILh4DBAMPXg8IABRMFwQH3BkFASkDAgcADA4HAQAEAwIeAQMiVgEGJ0kXAAUZgBUCAwUYex8AAAAKIJIMAwMBH08nBQAVmx4JAEsfCQUiCwgEAgEEBgYDDAEEHQEJLroECCOJLgICCysXAgYKCDANEAAAFBI2KQIAAzM5GQ4ABv8rBAouEgIBEgMBAwADBwIBAAACAScDCAR3AQIGCgkDAQQLDgcEBQ0jCggDARMe/x0AAQwrMBEAABYRDA0Cng0JBQ4GAgEAAgkBAQAAAAAAAQECCwEBJ0EFAQZT/x0AAAEc/3YAAAACAAAAAQAAAQAAAAACAAAAABcCAAAhAwAEAAIACwQDBAYKNAEEIEQRBTvHIAUNDkkqBwUHKiMLBQMADh9DKw0HBi/JGhUHF0ImBAMvCgYAGQcDBwECBgcFAQgCAScBBx1wCgYicBICEBdxJQcEBi1FFAkBARIYdyQEAgUwVRMGASBzGQoCZxoEACQHBAkDAgoHBwEHAgRDAAgjiwQIKFgeBQUTKx0OAgQxtBcGBQAXFpE6BAcKKj4YBQIWJxIHA1cSBgAtAwACAQMLAgEABAABFQACADABAAEAAAABAAAAAAABAAAAAAACA2z/FAAABCP/jwIAAhUnBwACAwUAAAAAAAAAAQIBAAEAAAUAAAMEAAABEAABASczBgABAVD/KwMBAAECAgAAAAAFAgEAAAAqBAEGUgICAEoIAAAAAAAEAgIHAAUJAAIFGwIDJnYZAAYcaCAABAZ3uRwFAAAKBzQYAwIEGyEMBQEfaxMBAtIVAQBrBgALAQQDCAQABwYEJwIFJcgHBSSGIAMLDS8fAgMHHiEPBQICDQ8rIgIAASwSDwgBLLIjDAeeNgQAFwQACAAMBwcBAAICAB8BAQQ2AQQMJhIDAg42GwYHDxIkDAEAAQsdUxYDAQlw/xoDABqnbwgEZicIAQoDBAUAAQcBAQACAQAEAAEFAwEABQUDAAEEBgAAAQAGAQAAAAAFJBoGAgUCRf8/CgQIQ0gLBAQFCgAABAQBAQEPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC+BOIBCgEHAAAAAAAAAAAAWktGaVgBMUsUuugBRAFDUyD5+BfyTPGII8oQrQXuAusO/wbVa7NJOxy/HZqW7wPnA7MH8kOgV+ApBhHPactZGwTncuga4XJkUJF6khwXfZoMDQ22L08fxg9HG2exB5gXpssZV7WBuSv5pfEsedH1SFWwldI9yRVjLXwd5h9Gj2ePhxsfhscp16mGyYYBvIn6sfgdY/5hv0F8yRdpHWkUaV9kB2BbA/sJ8QN5i22A7IBrQ8zB4RHc0PEB+cp8yP3IpXFM46cDlwE7DHsIMS0rnuU17pknU46ZNxMEkzUvRco2zidOq9FGY3YKziEvGX0ZcR/zD6M9iz0pHYtdA18JR08rD08nxydPvaPOY84xzTfXEdWB2ZB1AZs5uS0MPI5tjxeNJ2cPTS4pQTkuvSWNJ24PbhdDcwTjDTNdY4uqCa3AvYk9Dy4JvgrPCY8TjxkP+Eu5y6pG7k0DAAEBAQMDAAAQDQMBPNQKBBMc/ygBAxcuNhsBAAAIAQEGCAEDFDIEDAIauBMCARMOAQALDgIJBwYHCQEBCwMFIAIFHXEMDBquKAYIClc2BQsFIywWBQECCAojHAUDBBlWEA8CEEEgBADYEggBIAQBDwAIDQcDAgMABygABiZaBQIrNxYCAheEEQEDAw2QGQEAAQwdfw8HAgUZUiQBABeGIgcBZCYIAhcMDAUBAQgHAwAGAAkjAAgouQMJLJIqBwMKKRwABQcHMgwNAQIXF00pAwMDJy8eBQAJ9SUHDDcUAQATAQABAgcHBAEAAgQAJQMFAYYAAwQBBgEFBg4KBgQEDy0KBwUCEx3/IgIACSkjHQEAFwgOCwOcCwoEFAABAAEDBwEBAAAAAQMAAQMBAQQuRQMAA2b/IQIABTf/fQEAAAABAQEAAAADAAAAAQQFAAAAHwIAAD4CAAUBAAAHAQINAwsiAAggZw0FM+8fBAoYOygEBgkcLxQIAgARGDodDQQHOK4cDQQSXyoEBRwYAgERAQQHAQAKCgkBAwMDJgIGFYgOBCBfEgUNEWEiBQQIIEATCwMBExlfJwQDAydiFAUDJokXDQN9JgMAKAIABQECCQcDAQcEBEgADSacBAUtNx0DCBUxFhMBBTmWEQ4FARQZdj8GBAwiMxcFAhw8DwQDYiMFATQEAgEDAwgAAAADAQEgAAACJAAAAAEBAAAAAAAAAQEAAAAAAAIBdf8WAAABK/+HAAACECUGAAECAwEAAQEAAAAAAgEAAAAABQABBQYCAAEIAwECIiAFAQACXv8wBwAAAgMEAAAAAQUBAAAADicAAgFqEQACXwMDBAAAAAYBAAEDAA0ABgkhAgQrXhsEBR18JwEECWzLGQIBAAQLLBcBAAIaLgkBABtdDgQDxBgCAXILAQYCBAUHCQAHAAYsAQcnzwsEKqEhAQ0NLRoFAAMlDw4HAQAOEx4iAQADLBsOCQIyqSMLEIEsBQEWBwMIAAkGBgAABgQCIQECBC4BAgcnEQQECTkaAgEOHy8IAQAACRpzGQUCB4b+HAUAH7J2CwM8HA4BGgQABwADAgUAAAEBAQMAAAMEAgAFBQMAAAQHAAADAQUDAAAAAAogFwsJBARD/zUPBARMUAgHBQsIBAAFBQAAABMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAL4E4gELAQcAAAAAAAAAAABaS0ZpWAExSxS06AFEAUNTIPn4F/Bs8Rkj3jGpBc4BawzrDdtnI2kzHbsNnhTvAdcBsgNyK+BH4CsOEc9pmxkeFeZy6Dzj9mRRs30yPBddGjxNSTYXDQ9GG4Ib5zEnMlclCxlPtROxC/EV9URx0nVQXbAf0z3xHeIe5B/mD0YPZ5+nMy8PbxlPiemZygF9iXqw4h9HPsE+wa3IFMkqaBpoVuQeZLMjewvzKDmFb4DdgGvBjIHhEa3V+JH5yXzJ/cnrcVthbgVeYXskeyklZQufxSPJmS7TDJllEy0WJV5NShXZRU5j0U7H1iLOI20pfSnjL+ofgy2LDStfC28TWwtHTk9PT8fHBkfu505h/tPNJ12B1YLpwP1oKWmZSQwsjE+XJwkHTUdZPhliOSw/JUwjjEPOZ83m7MYxozzmoewBrcJtCG0RbgluW68bDxkbOQ/qR2zBqkNmcwMAAQIAAwEAAQ4KAgIx3woDESH/JQMDCzs4HAIAAAkCAQkDAQEXLwgKBBmPFwEEFQkAAQ8IAAsCBAgIBgEIBAchAgQZeggLJpohAw0OQjECBwk1MBMEAQAJCCIdAQUGFk8RDgAQRh0ECN4aBAErBQILAAkOBAAAAwIEJwIDJ2IEAypKGwAHH4sQBAIDG3QrAAAACxl5DwMBASBXHQIBHngbBwFTJQkCIgcKBAIBBgUFAgMAAzUABybyBAYcXSABAwQZDwMDCQcaBAwAAQ8kXyoBAwI3NxoHAhTxKwcJSyEEAg4EAQQAAggEAAAAAwAaAAQAVQIDBQcJBgAIBgkGAwQSJgkGBQQYI/8NAQATMDouAAAOCw4LA5EICwYSBQMAAAIIAgIAAAAAAQAABgIBASdHBQAEdv8SAAAFNf+CAwAAAQAAAAEAAAAAAAEBBxIBAAAfAwAAKgUACAABAQkFAwsDDC0ABjFYBwks1C4BCg0/HAUCByASBgcBAA4ZRiAPAwM5qBcVBBx0LAMDPhkEAQcGAggBBAkJBQAHAgMtAgMaigYIG10SAgoSXiMFAwYpXhIIAQIUG3wtBAIDMT4SCgEdihcPBGsYBwMbCAMFAQMJBwABAwMHRgEKJqUCAiItIwMDESwWCwYHLLETDQMAEiCvOwQFBStJHAIAFjURCANSEQMAJgQEAwEBCAAAAAAAABEAAAAkAAAAAAAAAAMbAAABAAALAgAAAQpZ/wwBDQEk/24AAAUFHAgACAIEAgACBQAAAAYBAAAAAAEDAAAAAwEAAQEAAQElOgEBAQZd/zAFAgADAwQAAAAABgEAAAALEAEAAp8YAQFjBgECAAABAwEABQEFCAAAEi4BAT2LHAIIJ1otBAUEXI4gAAEABQ0pFgAABBYmEAICKF8JAwTjIwEATwgACgEFBwkBAAUFBT4ABDTSBwkPVyoABQMMEgQDAhIDBQoAAg0iay8FAAEuSx8IASuxIgwHjCsEABEEAAoABwYEAgAEAAENAQIEFQIBByAOAQQSSgsHCQoZJA4HAQEFHDUMAAQDbv8eAwAc3mQCAUwZCAAYAgEDAAMHBAQAAAMCBwEDBAoCAQkDAAAECyoBAAIGDQYCAQIACxYVBQgJAVb/IQ4HDFdLEAcPFBILAQULAAEBIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA';
        $cmd = new BioTrackCmd ($iPP);
        return response()->json($cmd->update_user_face($iDP, $fACE.$fACE1.$fACE2),200);
    }

    //20
    public function update_user_data()
    {   
        $iPP = '10.203.231.200';
        $iDP = 9987;
        //fingerprints 3 y 6 (indices)
        $fINGERPRINTS = [
                                '',
                                '',
                                '',
                                'SmVTUzIxAAADJiQECAUHCc7QAAAbJ2kBAAAAg8sWpiYqAPIPtACEAAEpwABbAHsPRQBcJuQPrABhADsPUyaHANkPtQBbAGsp2ACeACQPJgCyJqIP3AC6AOsOaCa6AFEPuQAKADwr1QDQADINpADmJksPywD6APAP7iYXAbIPhQDhATYprwAzAS0PogA3JzYP8AA4AW4PWCZFATgPngCDAbYptPPL9rt64BOurcsEeX61e3aKnc2G5wMPeYaL/AU91ouP9+OT30UwGlYoiYGZ+xu9O1GIgTJxLI9k/g4pewvfeyPrgA8tNHIMHQbR9+eRAd1iF3cXFgevh/zeDwlufz+HfwFxpVsLsXri++77pic3BVeHkvmeg4BdJAEvBUuHbIpxpVqDQigAIO4BAtscWgYAlRCidPwoAbcScYBVBHDD5AgAnxRpwaFsByaBFWd+DgB+Hn7jasFkef0Nxc8lUcBsZsBpEcXXNaCQwJDAZP+yBwOePAA7RwUAdUF3tgYAt0QDOP0QA5hbgMTC/4k6wmZMCACxYQD/9MFBMAAPc6CHwqzDwOfBwXvAdMHTAQlcnX5qxJN+BXRmPgAPlp5wfATBxqT+clbAchLFsZhSomrBe8DBB8HC5AwAuZ4J/DvC/mr+/1MKAN1lIv17Nv4QALGiqKLB5sNmwnTBGMQWr4ZzasPAw8MHxP3nemRsFgDga6TBvcfEcm9raU4UAja3qYd3wcMEo2FZDAC7vRr9OWTB5sP+/cYKACW+M+RHwFoKAGoFU8LYhWgMAKzIlpB45f+MDQCxypXDZOfBwcT9w8DXAN3srMLEwcjEVn7C53oJAMHMMDpkfyoBtdJJi3G9xA4mutIwNYuQswYD8tIwWMEJACbUKGJTwh8BFdd0wcLnwISGxMTBB8DC58HBwcH+wgXA/eXDwwsAud/4ZMLngsQIAF3piWrDewsAY+lGWYH/xjkAFfG3wcIFwcPnw8LAwsLDAMNhosHB/2rEZswAyNg2d8P+kwbVhSsSwY0DEK826MAANmY4OsIdEdZLpx5EwMFfw8IOm3tWw05SQgALhgEDJgpFUgA=',
                                '',
                                'TRtTUzIxAAAEWFsECAUHCc7QAAAcWWkBAAAAhIUip1hJAAUOnwCgAABWfQBmAHEPrwBsWPIPGABuAKwPyFh7AIQP3QBBABZXFwCPAFwPXwCsWGYP3gCsAE8PT1iyAN4PxAB4AH9XUQDHAFQPpgDDWFMPvADTAKIPA1nVACQPqAAZAFBWIADgAFsPxAHmWKMPhgDzABEPWVj6AEYPLQDFAVBXjwAIATwPcAAJWS4PCwERAW0NBFkUAaENEAHbAZ5VyQAiASQPiQAtWUoPsQApAekPeFg0AToPOADzAVdXVQA2AUYPMAA7WQgPwQPjlGaDRVv/lY+BjYHLbfM0iIWP8XvznwwTIz6PEXWPgfb9AcmvisOb6vT6g0NTLuxTFj8CpxCyIlYl2Y3CjMaHUU7v8GYrLQUgeZ+hsAHOdHcNTBbttvrdrYT/nl5/GbaXgg7bWgnWCQMnsIAX/CMBGJqS2ieTNne39E782qEqEFMJ9WqPDmNImAd1D9r2jQsNSJII0Pv1Ce+bnax8+UaT0frE93NGYASd+gcEjAodp/bwxvYXABbwEVIsD+cC5fx49z5WV3NCa0thB6mLDAAgPwECnebAAFhaNXB1AwBvNISYCwB3OH3CBk7EaA4Aqjp6TgWExDpyDACNRX0H/8aawMBVwg4Adk+HmG7BwnNrEsXPXdF3eMGJRXvJAG85Zf/BScBdBwUE+2MA/kcJABJjjTHBexAAm2W/wYeYdcHB/XYNxXhsLIhJwMFFBsWjbFtNwBIAr3BDwceZwMLAeP/DO8BXXwGxcQM3QtQAzSKHwML+xf8GeH86DADZg4zDO4PG3IUDAOGDDDoDBLmJE8AMAJZjbYfRRMIFAJ6nMikUWJasacKGca12xEMADq6ewmIHwXDLgv7Ag8H+BVUVWMG6gMLDwlfAxSpmwh0BD7lbdHOawHqLwf/AB3ZHmFoGAMi9Ce/BA1jBv33Cw8JSEAQ+xdo1KDP/Oj4KWF/JV8JbcztU+1QBTspXwWsFwDqnHgEXypr/t4uU1H+EwMDAaPvACVhizFBbcFr0GAVb0aJ5wmyWB4vFmcBaYAsAoxlXxpmIcMAXAQIbp4SbdMLDwoN+oW0AWBzgXnEKAGLgV5r+xWd0BQDn5FIaAgEE5ifA1QCOqtLAJP3A/DhU+5j9BQCE90m3CQT4/kCEcsME1V0FEV0GECwDVp7+D0i1Cb37+fc5wMSYlgcQhApDqmoDSI8LPcDCZtMRDlWowWrBw8MHw8ecwcHDwcDCOoMNSLgQLf/DwaLCDUi1ETeUwsBOExSmEqBKw8PGA8THmsDCwMLAe9ARCUKjWMDCwcUAxMedwcLAwMLCqQcUkSUkapUEEI0sSA4FEE4tSVrDELZ1LMHBhBMR1i2Umv3+WMTPtQVnilwRejlAwv/BEHthO8HBBBBR/0k4WxFXOkbBBNU3Pws1EREWO5cB/fqnRdnGwsDBBJlWGgELQwE=',
                                'SlNTUzIxAAADEBQECAUHCc7QAAAbEWkBAAAAgj0VfhA6AA4OkgCHAI0eeQBJAIkOeABXEKUPfwBfANMPbRBzAH0PrwC4AJ4flQCCAJEPjACJEG4PIQCaACkPchCdAA8PjQBmAI4fXQCsAG8PCAC7ECYPgwDHAEkPVhDTAAAPpAA8ADIfdwAfAT4PfgA1ETIPXABKAQUPpBBKAUgOwYREgrHpgIJpB0p5AHwuZuz/KgtvGP4XHp7ImkKJ4WrT7kFjXA+y+0MRLPc5FZt+PgKCh+NjhW+if7fv2aO4hzGHfIO+/UIBPGNZYr8CB4/rnxafwRGmfG+MSpK+dFTjtvf7p4MDXoEkH2L7re8DBxr3mJXCe7uPGRcSD7ibOeYAIC8BxPMa3AgAjxkT/4T9khcBfxoXwMAF//4XAXgkE1MqxgDKLCX9DwBZKcP+w9EpRGXADgCZNgruZP7/Q8DABQMDY0aJwQUAT4eAwHQEAMBYJFjAAIFNDf3//wcAklh5af/CFAAYYyjC/9D/Ny7///8FVsMcAYFjGlY2oMELEGtug8J+g8YAcWMN/ggAanW/c5IXARV96UY1zgBjcwj//sA2wIcDA1WKccEVACNQ5/1QPf4wVP/BBUcJEGycgIjBwacTAz6f6UD+/yqEwFFEAgAsn2nAywB3sBHA/f8+UwXAwxoBWattdHmlAwPBuyLABADMeSlfCAELweJMQYX8/S5Fwf/B/v/IAILTlsTCxMKAmf8NEH7Ij8PCxbxkwkwNAIfLHi8E/kVmEQBZzfokOjH8R1kLAFHUXgXDZ9L+lg8AWdQ4/SA7PCkKAGvxuMfH0MLAhBkAAj3M/tL9wDcj//w6/sPvwf7Awf5bzQBj6FeQgggAcjwi/igmCQCl/DAFQMPT/QsAa/0n6iP95sAHEGUALew0BgBiDFfFaQbVZA0tVf4aEAsRFsIx7zck/f3A/wX+wu7BwMD/wQXVdiAqLxgQlFjMQYPCncTEoMDBwASMFABHX6f8M8H2/vrr/f/+//7/Ov397VNCAAtDAcUACFVTAA==',
                                '',
                                '',
                                ''];
        $nAME = 'PepitoActualizado';
        $cmd = new BioTrackCmd ($iPP);
        $dATA = $this->data($iDP, $nAME, $fINGERPRINTS);
        return response()->json($cmd->update_user_data($dATA),200);
    }

    //21
    public function sync_clock()
    {   
        $iPP = '10.203.41.39';
        $cmd = new BioTrackCmd ($iPP);
        return response()->json($cmd->sync_clock(),200);
    }

    //22
    public function get_log()
    {
        $iPP = '10.203.231.193';
        $cmd = new BioTrackCmd ($iPP);
        return response()->json($cmd->get_log(),200);
    }
    //FIN FUNCIONES DE PRUEBA

    public function actualizarHuella(Request $request)
    {
        //Validacion de campos que se pueden recibir
        $this->validate($request, [
            'IdUser' => 'required',
            'IP' => 'required',
            'Type' => 'required'
        ]);
        $cmd = new BioTrackCmd (request('Type'), request('IP'));
        $IdUser = request('IdUser');

        /*NOTA:
            para insertar una huella debe ser el dedo correcto el dispositivo
            ni la funcion notifican de que esta ingresando una huella correcta pero del dedo incorrecto*/
        $fingerprints = [
                                '',
                                '',
                                '',
                                '',
                                '',
                                'SsVTUzIxAAADhocECAUHCc7QAAAbh2kBAAAAg6sbfYZQAIwPawCZAIqJpQBeAA4P2gBhhnAPmwB1AMgPuYZ+AIwPmwBGAIuJuQCHABAPrQCIhgcPkQCZAEAPwoaoABUPoQBvAIeJTQCxAHsPBADJhhUPgwDSAMAP3ob3ABoPwQA7AJOJIAAHAWkPdwAch4YPXgAjAa0PyYYqASMPMgDqAWKJawAwAfYPfwA1h48PhAA5Aa8PtoZIAY0PRQCLAV+JYAYCghuAJP44Ag5+wQK+iluGDG0mbz/7tYSAAoEGQX5yBIKAfHxKgPx7PIb1i88FiQU+fNeMHQII/sn/65CuACIFWAL99rf+43Qfez77LYYPk6+FV4GCg3R13I8TCbf6IHtBjypsSgsrA4IPLnwMZ875OXXrA4yOxJXxn7qZjwXRfRb4LZGZjzac2us8AaUKpXdrByRbvAHObbILC/0I7vr1f2+6AeU8AoQhGx4EADrpA1GBAT8zBv9FBQYDvDkMVv4JAMtF9603wAgACE8/PUeFAZpPDMMDxYJQicAIAANc9wUwVo8Bb10JwP8E/sPbCwAjYf0vqEMAhqRiEMAMAM1490Yx/11UAwB7gA94DQAIhfAwkcFWgAGfhgzAP88Abw4CRP9V/wjFZIkAeoQDAGuOzMAHhpSaBjoLAEichdDBwlnBDABbpopEVHTBbAQAAagQyQYApawJ/pD/D4acrYPAwVqfggeGw60adwYAgrJ538APALzHiTrCbkT+e2cFAMQME8NE/AoAB8rw/cHCswkAhLUAQQVECYaGzgP/QP+nBQNFzxrCPQoAutKD/V17CwCH1cb+w6n+/10UAAgk7fyxwURPwP7/kMAWhgj668H9SwTB/b46wv3AWw3Fvf4VdoD/wMF70hAEj+b+V0xH/zorScICECALZ8DCEKyYiHllCBBa5nHBRMHBTxYQCOLnXXlSVDX/wP2lwASWXydnamoN1cYrGMOIf8CABtXOKJg5/wUQLi6iwYyBEWwu98DAOTAGlssvIsA2BdUyMObBbxgQCDQn/0hG/lQ9M1X+8woTMDaQjf/Bk8MQg75xgMAHEIj9/fx6KAMQvjoiOgUTBDxnwHoXEM1C4Ub+/8BASjXswfytBxCwRpChBxITtFneQ8D//IP9w33B/lIGEH2d5P19/P8DEI1YKPlRxAELQwEAAM5FUYY=',
                                '',
                                '',
                                '',
                                ''];

        $insertarhuella = $cmd->update_user_fingerprint($IdUser, 5, $fingerprints);

        return response()->json(['respuesta'=> $insertarhuella],200);
    }
}